[sources.filesystem.credentials]
aws_access_key_id = "your-key-id"
aws_secret_access_key = "your-scret-key"

[destination.redshift.credentials]
database = "dev"
password = "your-password"
username = "your-username"
host = "e-commerce-sales.xxxxxxxxxxxx.us-east-1.redshift-serverless.amazonaws.com"
port = 5439
connect_timeout = 10