version: 2

sources:
  - name: entry_shopee
    database: sales_db
    schema: entry
    tables:
      - name: entry_shopee

  - name: entry_ml
    database: sales_db
    schema: entry
    tables:
      - name: entry_mercadolivre
      - name: entry_mercadolivre__context__flows
      - name: entry_mercadolivre__mediations
      - name: entry_mercadolivre__order_items
      - name: entry_mercadolivre__order_items__item__variation_attributes
      - name: entry_mercadolivre__payments
      - name: entry_mercadolivre__payments__available_actions
      - name: entry_mercadolivre__tags
      - name: entry_mercadolivre_sh
      
  - name: supplies
    database: sales_db
    schema: supplies
    tables:
      - name: product_sku_cost
        external:
          location: /input_data/clean/clean_cost_data.csv
          file_format: csv
      - name: kit_components
        external:
          location: /input_data/clean/kit_components.csv
          file_format: csv