name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      CODE: ${{ secrets.CODE }}
      EXPIRES_IN: ${{ secrets.EXPIRES_IN }}
      REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      SCOPE: ${{ secrets.SCOPE }}
      SELLER_ID: ${{ secrets.SELLER_ID }}
      TOKEN_TYPE: ${{ secrets.TOKEN_TYPE }}
      USER_ID: ${{ secrets.USER_ID }}
      SHIPPING_ID_TEST_1: ${{ secrets.SHIPPING_ID_TEST_1 }}
      LIST_COST: ${{ secrets.LIST_COST }}
      SHIPPING_SAMPLE: ${{ secrets.SHIPPING_SAMPLE }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: set_python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: install_dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: build docker image
      run:
        docker build -t airflow_e_commerce_sales:v001 .

    - name: create network
      run:
        docker-compose up -d

    - name: Run tests
      run: |
        pytest --cov=./ --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: build docker image
        run:
          docker build -t airflow_e_commerce_sales:v001 .

      - name: create network
        id: docker_network
        run:
          docker-compose up -d
      
      - name: wait for network
        id: delay
        needs: docker_network
        run: |
          echo "Waiting for Airflow..."
          sleep 30

      - name: check airflow permissions
        run:
          docker exec e-commerce-sales-pipeline-airflow-scheduler-1 ls -l /opt/airflow/dags

      - name: run '00_create_IAC'
        needs: delay
        run:
          docker exec e-commerce-sales-pipeline-airflow-webserver-1 airflow dags trigger 00_create_IAC
      
      - name: run '01_extract_data'
        run:
          docker exec e-commerce-sales-pipeline-airflow-webserver-1 airflow dags trigger "01_extract_data"
      
      - name: run '02_clean_data'
        run:
          docker exec e-commerce-sales-pipeline-airflow-webserver-1 airflow dags trigger "02_clean_data"
      
      - name: run '03_load_data'
        run:
          docker exec e-commerce-sales-pipeline-airflow-webserver-1 airflow dags trigger "03_load_data"

      - name: run '04_transform_data'
        run:
          docker exec e-commerce-sales-pipeline-airflow-webserver-1 airflow dags trigger "04_transform_data"
